Repository deshima-dev/decode, pull requests merged in 2024-09, with the labels that each got.

#208 Add signal spike removal
  decode/qlook.py
Labels: bug

#210 Release v2024.9.0
  CITATION.cff
  LICENSE
  README.md
  decode/__init__.py
  pyproject.toml
Labels: release

#207 Update definition of major/minor axes of 2D Gaussian fitting
  decode/qlook.py
Labels: feature

#213 Release v2024.9.1
  CITATION.cff
  README.md
  decode/__init__.py
  pyproject.toml
Labels: release

#215 Fix reversed sky longitude axis in daisy/raster qlook
  decode/qlook.py
Labels: bug

#217 Release v2024.9.2
  CITATION.cff
  README.md
  decode/__init__.py
  pyproject.toml
Labels: release
