Repository deshima-dev/decode, pull requests merged in 2024-08, with the labels that each got.

#191 Add moving average (by DataArray.rolling) to qlook commands
  decode/qlook.py
Labels: feature

#194 Release v2024.8.0
  CITATION.cff
  README.md
  decode/__init__.py
  pyproject.toml
Labels: release

#190 Add 2D Gaussian fitter to qlook commands
  decode/qlook.py
Labels: feature

#196 Release v2024.8.1
  CITATION.cff
  README.md
  decode/__init__.py
  decode/qlook.py
  pyproject.toml
Labels: release

#198 Fix 2D Gaussian fitting and related title formatting of qlook
  decode/qlook.py
Labels: bug

#201 Release v2024.8.2
  CITATION.cff
  README.md
  decode/__init__.py
  pyproject.toml
Labels: release

#203 Fix aspect ratio of qlook map images
  CITATION.cff
  README.md
  decode/__init__.py
  decode/qlook.py
  pyproject.toml
Labels: bug, release

#205 Add utility to get phase label of 1D DataArray
  CITATION.cff
  README.md
  decode/__init__.py
  decode/utils.py
  pyproject.toml
  tests/test_utils.py
Labels: feature, release
