Repository deshima-dev/decode, pull requests merged in 2024-07, with the labels that each got.

#163 Add qlook commands for X/Y scan
  .devcontainer/devcontainer.json
  .github/workflows/gh-pages.yaml
  .github/workflows/pypi.yaml
  .github/workflows/tests.yaml
  CITATION.cff
  README.md
  decode/__init__.py
  decode/qlook.py
  poetry.lock
  pyproject.toml
Labels: feature, release

#165 Fix missing conditional branches for X/Y scan
  CITATION.cff
  README.md
  decode/__init__.py
  decode/qlook.py
  pyproject.toml
Labels: bug, release

#167 Update output image by raster command
  CITATION.cff
  README.md
  decode/__init__.py
  decode/qlook.py
  pyproject.toml
Labels: feature, release

#169 Add qlook command for daisy scan
  decode/assign.py
  decode/qlook.py
Labels: feature

#171 Update qlook options for loading DEMS
  CITATION.cff
  README.md
  decode/__init__.py
  decode/qlook.py
  pyproject.toml
Labels: feature, release

#173 Fix qlook options for min/max frequencies
  CITATION.cff
  README.md
  decode/__init__.py
  decode/qlook.py
  pyproject.toml
Labels: bug, release

#175 Add qlook option for debugging
  CITATION.cff
  README.md
  decode/__init__.py
  decode/qlook.py
  pyproject.toml
Labels: feature, release

#177 Use dems v2024.7.2 or later
  CITATION.cff
  README.md
  decode/__init__.py
  poetry.lock
  pyproject.toml
Labels: feature, release

#181 add atm-correction for raster
  decode/qlook.py
Labels: feature

#185 Fix labeling method of qlook daisy command
  CITATION.cff
  README.md
  decode/__init__.py
  decode/qlook.py
  pyproject.toml
Labels: bug, release
