Repository deshima-dev/decode, pull requests merged in 2024-11, with the labels that each got.

#221 Implement ABBA-based analysis for chop-and-nod observations
  decode/qlook.py
Labels: feature

#223 Release v2024.11.0
  CITATION.cff
  README.md
  decode/__init__.py
  pyproject.toml
Labels: release

#225 Fix release date
  CITATION.cff
Labels: bug, release
