Repository deshima-dev/decode, pull requests merged in 2025-04, with the labels that each got.

#229 Pointing結果のTOML出力の実装
  decode/qlook.py
  poetry.lock
  pyproject.toml
Labels: feature

#231 Update project dependencies
  CITATION.cff
  README.md
  decode/__init__.py
  decode/select.py
  poetry.lock
  pyproject.toml
  tests/test_convert.py
  tests/test_plot.py
  tests/test_select.py
Labels: release, env

#233 Remove deprecated data type (numpy.float_)
  CITATION.cff
  README.md
  decode/__init__.py
  decode/fit.py
  pyproject.toml
  tests/test_assign.py
Labels: bug, release

#235 Fix return data type of DataArray in convert.units
  CITATION.cff
  README.md
  decode/__init__.py
  decode/convert.py
  pyproject.toml
Labels: bug, release
